# Generated by Django 4.0.2 on 2022-02-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('balance', models.CharField(max_length=240)),
            ],
            options={
                'ordering': ['-rank'],
            },
        ),
    ]
